# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
variables:
  buildConfiguration: 'Release'
stages:
- stage: CI
  displayName: CI stage
  jobs:
  - job: build
    displayName: Build
    steps:
    - script: echo This is a BUILD job
      displayName: 'Build project'
- stage: CD
  displayName: CD stage
  jobs:
  - deployment: deploy
    displayName: Deploy
    environment: Webserver
    strategy: 
      runOnce:
        deploy:
          steps:
          - script: echo This is a DEPLOYMENT job
            displayName: 'Deploy project'